"use client";
import { useEffect } from "react";
import OverflowProvider, { useOverflowContext } from "./context/scrollContext";
import "./globals.css";

/* export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}; */

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const { overflowHidden } = useOverflowContext();
    useEffect(() => {
        console.log("overflowHidden : ", overflowHidden);
    }, [overflowHidden]);

    return (
        <html lang="en">
            <OverflowProvider>
                <body style={{ overflow: overflowHidden ? "hidden" : "auto" }}>
                    {children}
                </body>
            </OverflowProvider>
        </html>
    );
}
